### ISSUE TITLE
Unable to annotate French entity preceded by an elided word

### ISSUE THREAD

**Issue by kleag** [danovw/annotate_translation#6]
In French, some words are elided in front of others. For example, the preposition "de" is elided as "d'" in front of words starting by a vowel. We write
"[…] d'émissions de télévision japonaises […]" 
instead of 
"[…] de émissions de télévision japonaises […]".

Currently the GUI refuse to annotate "émissions de télévision japonaises" as an entity because there is no space before (See attached screenshot. It should probably accept all punctuation characters but only `'` could be enough.

![screenshot](https://user-images.githubusercontent.com/3354467/190347490-488b88f6-7592-484a-a818-1525d7977177.png))

**Comment by danovw** [comment]
Hi, I have modified the code to handle this special case.
